### ISSUE TITLE
Code Run Error

### ISSUE THREAD

**Issue by taichanghong** [jinquanaccount/BCWSP#1]
I am running your code Parameter_Calibration20230216.py with the error: traceback (most recent call last):
  File "D:/BCWSP-main/PerformanceTest20230216.py", line 3, in <module>
    from Resources.scheduler_comparison20230216 import MultiScheduler
  File "D:\BCWSP-main\Resources\scheduler_comparison20230216.py", line 6, in <module>
    Importing gantt from plotGantt
ModuleNotFoundError: No module named 'plotGantt', it seems that this plotGantt function is missing, I hope to get your help on the code of the plotGantt module.

**Comment by jinquanaccount** [comment]
您好，邮件已收到，谢谢，预祝答辩顺利~

**Comment by taichanghong** [comment]
Code run error: Traceback (most recent call last):
  File "D:/BCWSP-main/PerformanceTest20230216.py", line 5, in <module
    Importing DAG, TempTask from JsonDataGenerationBC
Module not found error: there is no module named "JsonDataGenerationBC". Looking forward to getting your help!

**Comment by taichanghong** [comment]
上面的报错暂时解决，感谢您共享的代码

**Comment by ccccccccccccccccccce** [comment]
Hello, Senior!    I am running your code scheduler_comparison20230216.py with the error: python -u "d:\python\project\BCWSP-main\BCWSP-main\Resources\scheduler_comparison20230216.py"
Traceback (most recent call last):
  File "d:\python\project\BCWSP-main\BCWSP-main\Resources\scheduler_comparison20230216.py", line 6, in <module>
    from plotGantt import gantt
ModuleNotFoundError: No module named 'plotGantt'
, it seems that this plotGantt function is missing, I hope to get your help on the code of the plotGantt module.

**Comment by jinquanaccount** [comment]
您好，邮件已收到，谢谢，预祝答辩顺利~
